### ISSUE TITLE
[BUG] Documents uploaded not appearing in list

### ISSUE THREAD

**Issue by shanekark** [orrekie/orrekie.github.io#8]
Document upload pop-up appears to be functional. After clicking upload, user is prompted with a notification in the top right corner, but, no document appears in the list or anywhere else in the project.

![Image](https://user-images.githubusercontent.com/118477378/211541459-c4aeb099-05ad-4e81-a178-ed61f18534dc.png)

![Image](https://user-images.githubusercontent.com/118477378/211541498-830edb15-bc1e-457b-8bfa-96c9d1fe9afe.png)

![Image](https://user-images.githubusercontent.com/118477378/211541532-2037b703-d071-4fa2-9283-8f4ab33f6e2c.png)

**Comment by giuliobosco** [comment]
Fixed.

CDN CORS origin was set only for the old url, now has been setted to `*` in `config/config,yml` on `red.bomaidea.xyz` server.

**Comment by giuliobosco** [comment]
Issue for [orrekie](https://github.com/orrekie/orrekie) repository.
